version: '3.1'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  iguagile-api:
    image: ghcr.io/iguagile/iguagile-engine:latest
    ports:
      - "8080:80"
    environment:
      REDIS_HOST: redis:6379

