// Code generated by protoc-gen-go. DO NOT EDIT.
// source: room.proto

package room

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateRoomRequest struct {
	ApplicationName      string   `protobuf:"bytes,1,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	MaxUser              int32    `protobuf:"varint,4,opt,name=max_user,json=maxUser,proto3" json:"max_user,omitempty"`
	RoomToken            []byte   `protobuf:"bytes,5,opt,name=room_token,json=roomToken,proto3" json:"room_token,omitempty"`
	ServerToken          []byte   `protobuf:"bytes,6,opt,name=server_token,json=serverToken,proto3" json:"server_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoomRequest) Reset()         { *m = CreateRoomRequest{} }
func (m *CreateRoomRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRoomRequest) ProtoMessage()    {}
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{0}
}

func (m *CreateRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomRequest.Unmarshal(m, b)
}
func (m *CreateRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomRequest.Marshal(b, m, deterministic)
}
func (m *CreateRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomRequest.Merge(m, src)
}
func (m *CreateRoomRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRoomRequest.Size(m)
}
func (m *CreateRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomRequest proto.InternalMessageInfo

func (m *CreateRoomRequest) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

func (m *CreateRoomRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *CreateRoomRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateRoomRequest) GetMaxUser() int32 {
	if m != nil {
		return m.MaxUser
	}
	return 0
}

func (m *CreateRoomRequest) GetRoomToken() []byte {
	if m != nil {
		return m.RoomToken
	}
	return nil
}

func (m *CreateRoomRequest) GetServerToken() []byte {
	if m != nil {
		return m.ServerToken
	}
	return nil
}

type CreateRoomResponse struct {
	Room                 *Room    `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoomResponse) Reset()         { *m = CreateRoomResponse{} }
func (m *CreateRoomResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRoomResponse) ProtoMessage()    {}
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{1}
}

func (m *CreateRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomResponse.Unmarshal(m, b)
}
func (m *CreateRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomResponse.Marshal(b, m, deterministic)
}
func (m *CreateRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomResponse.Merge(m, src)
}
func (m *CreateRoomResponse) XXX_Size() int {
	return xxx_messageInfo_CreateRoomResponse.Size(m)
}
func (m *CreateRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomResponse proto.InternalMessageInfo

func (m *CreateRoomResponse) GetRoom() *Room {
	if m != nil {
		return m.Room
	}
	return nil
}

type Room struct {
	RoomId               int32             `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RequirePassword      bool              `protobuf:"varint,2,opt,name=require_password,json=requirePassword,proto3" json:"require_password,omitempty"`
	MaxUser              int32             `protobuf:"varint,3,opt,name=max_user,json=maxUser,proto3" json:"max_user,omitempty"`
	ConnectedUser        int32             `protobuf:"varint,4,opt,name=connected_user,json=connectedUser,proto3" json:"connected_user,omitempty"`
	Server               *Server           `protobuf:"bytes,5,opt,name=server,proto3" json:"server,omitempty"`
	ApplicationName      string            `protobuf:"bytes,6,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	Version              string            `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	Information          map[string]string `protobuf:"bytes,8,rep,name=information,proto3" json:"information,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{2}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *Room) GetRequirePassword() bool {
	if m != nil {
		return m.RequirePassword
	}
	return false
}

func (m *Room) GetMaxUser() int32 {
	if m != nil {
		return m.MaxUser
	}
	return 0
}

func (m *Room) GetConnectedUser() int32 {
	if m != nil {
		return m.ConnectedUser
	}
	return 0
}

func (m *Room) GetServer() *Server {
	if m != nil {
		return m.Server
	}
	return nil
}

func (m *Room) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

func (m *Room) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Room) GetInformation() map[string]string {
	if m != nil {
		return m.Information
	}
	return nil
}

type Server struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	ServerId             int32    `protobuf:"varint,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Token                []byte   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	ApiPort              int32    `protobuf:"varint,5,opt,name=api_port,json=apiPort,proto3" json:"api_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Server) Reset()         { *m = Server{} }
func (m *Server) String() string { return proto.CompactTextString(m) }
func (*Server) ProtoMessage()    {}
func (*Server) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{3}
}

func (m *Server) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Server.Unmarshal(m, b)
}
func (m *Server) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Server.Marshal(b, m, deterministic)
}
func (m *Server) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Server.Merge(m, src)
}
func (m *Server) XXX_Size() int {
	return xxx_messageInfo_Server.Size(m)
}
func (m *Server) XXX_DiscardUnknown() {
	xxx_messageInfo_Server.DiscardUnknown(m)
}

var xxx_messageInfo_Server proto.InternalMessageInfo

func (m *Server) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Server) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Server) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *Server) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *Server) GetApiPort() int32 {
	if m != nil {
		return m.ApiPort
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateRoomRequest)(nil), "CreateRoomRequest")
	proto.RegisterType((*CreateRoomResponse)(nil), "CreateRoomResponse")
	proto.RegisterType((*Room)(nil), "Room")
	proto.RegisterMapType((map[string]string)(nil), "Room.InformationEntry")
	proto.RegisterType((*Server)(nil), "Server")
}

func init() { proto.RegisterFile("room.proto", fileDescriptor_c5fd27dd97284ef4) }

var fileDescriptor_c5fd27dd97284ef4 = []byte{
	// 454 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xcd, 0x6e, 0x13, 0x31,
	0x18, 0xd4, 0x26, 0xfb, 0x97, 0x6f, 0x0b, 0x0d, 0x06, 0xc1, 0x36, 0x08, 0x11, 0x22, 0x21, 0x85,
	0xcb, 0x22, 0x05, 0x21, 0x55, 0x1c, 0xb8, 0x00, 0x87, 0x5c, 0x50, 0x65, 0xe0, 0xbc, 0x32, 0xd9,
	0x0f, 0x61, 0xb5, 0x6b, 0x6f, 0x6d, 0x27, 0xb4, 0x17, 0xde, 0x91, 0xf7, 0xe0, 0x21, 0x90, 0x3f,
	0x2f, 0xe9, 0x96, 0x56, 0xe2, 0xe6, 0x19, 0x8f, 0x7f, 0xc6, 0x33, 0x06, 0x30, 0x5a, 0xb7, 0x55,
	0x67, 0xb4, 0xd3, 0x8b, 0x5f, 0x11, 0xdc, 0x7b, 0x67, 0x50, 0x38, 0xe4, 0x5a, 0xb7, 0x1c, 0xcf,
	0xb7, 0x68, 0x1d, 0x7b, 0x01, 0x53, 0xd1, 0x75, 0x67, 0x72, 0x23, 0x9c, 0xd4, 0xaa, 0x56, 0xa2,
	0xc5, 0x32, 0x9a, 0x47, 0xcb, 0x09, 0x3f, 0x1c, 0xf0, 0x1f, 0x45, 0x8b, 0xac, 0x84, 0x6c, 0x87,
	0xc6, 0x4a, 0xad, 0xca, 0x11, 0x29, 0xfe, 0x42, 0x36, 0x83, 0xbc, 0x13, 0xd6, 0xfe, 0xd0, 0xa6,
	0x29, 0xc7, 0x34, 0xb5, 0xc7, 0xec, 0x08, 0xf2, 0x56, 0x5c, 0xd4, 0x5b, 0x8b, 0xa6, 0x8c, 0xe7,
	0xd1, 0x32, 0xe1, 0x59, 0x2b, 0x2e, 0xbe, 0x58, 0x34, 0xec, 0x49, 0xb8, 0x5f, 0xed, 0xf4, 0x29,
	0xaa, 0x32, 0x99, 0x47, 0xcb, 0x03, 0x3e, 0xf1, 0xcc, 0x67, 0x4f, 0xb0, 0x67, 0x70, 0x60, 0xd1,
	0xec, 0xd0, 0xf4, 0x82, 0x94, 0x04, 0x45, 0xe0, 0x48, 0xb2, 0x78, 0x09, 0x6c, 0x68, 0xc9, 0x76,
	0x5a, 0x59, 0x64, 0x47, 0x10, 0xfb, 0x5d, 0xc8, 0x47, 0xb1, 0x4a, 0x2a, 0x9a, 0x24, 0x6a, 0xf1,
	0x7b, 0x04, 0xb1, 0x87, 0xec, 0x11, 0x64, 0x74, 0xb6, 0x6c, 0x48, 0x96, 0xf0, 0xd4, 0xc3, 0x75,
	0xe3, 0x1f, 0xc4, 0xe0, 0xf9, 0x56, 0x1a, 0xac, 0xf7, 0x9e, 0xbc, 0xdd, 0x9c, 0x1f, 0xf6, 0xfc,
	0xc9, 0x6d, 0xd6, 0xc6, 0xd7, 0xad, 0x3d, 0x87, 0xbb, 0x1b, 0xad, 0x14, 0x6e, 0x1c, 0x36, 0x43,
	0xef, 0x77, 0xf6, 0x2c, 0xc9, 0x9e, 0x42, 0x1a, 0xec, 0x90, 0xfb, 0x62, 0x95, 0x55, 0x9f, 0x08,
	0xf2, 0x9e, 0xbe, 0x35, 0x9e, 0xf4, 0xbf, 0xf1, 0x64, 0xd7, 0xe3, 0x39, 0x86, 0x42, 0xaa, 0x6f,
	0xda, 0xb4, 0x24, 0x2e, 0xf3, 0xf9, 0x78, 0x59, 0xac, 0x1e, 0xd2, 0xb3, 0x54, 0xeb, 0xab, 0x89,
	0x0f, 0xca, 0x99, 0x4b, 0x3e, 0x94, 0xce, 0xde, 0xc2, 0xf4, 0x5f, 0x01, 0x9b, 0xc2, 0xf8, 0x14,
	0x2f, 0xfb, 0x92, 0xf8, 0x21, 0x7b, 0x00, 0xc9, 0x4e, 0x9c, 0x6d, 0xb1, 0xaf, 0x45, 0x00, 0x6f,
	0x46, 0xc7, 0xd1, 0xe2, 0x27, 0xa4, 0xc1, 0x10, 0x63, 0x10, 0x7f, 0xd7, 0xd6, 0xf5, 0xcb, 0x68,
	0xec, 0xb9, 0x4e, 0x1b, 0x47, 0xcb, 0x12, 0x4e, 0x63, 0xf6, 0x18, 0x26, 0x7d, 0xe8, 0xb2, 0xe9,
	0x1f, 0x35, 0x0f, 0xc4, 0xba, 0xf1, 0x07, 0x85, 0x2a, 0xc4, 0x54, 0x85, 0x00, 0x7c, 0x0c, 0xa2,
	0x93, 0x35, 0x6d, 0x95, 0x84, 0x18, 0x44, 0x27, 0x4f, 0xb4, 0x71, 0xab, 0xf7, 0x50, 0x78, 0x97,
	0xfe, 0x0e, 0x72, 0x83, 0xec, 0x35, 0xc0, 0x55, 0x5d, 0x18, 0xab, 0x6e, 0x7c, 0x87, 0xd9, 0xfd,
	0xea, 0x66, 0x9f, 0xbe, 0xa6, 0xf4, 0x81, 0x5e, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x1f,
	0xe1, 0x67, 0x4e, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RoomServiceClient is the client API for RoomService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RoomServiceClient interface {
	CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*CreateRoomResponse, error)
}

type roomServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoomServiceClient(cc grpc.ClientConnInterface) RoomServiceClient {
	return &roomServiceClient{cc}
}

func (c *roomServiceClient) CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*CreateRoomResponse, error) {
	out := new(CreateRoomResponse)
	err := c.cc.Invoke(ctx, "/RoomService/CreateRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoomServiceServer is the server API for RoomService service.
type RoomServiceServer interface {
	CreateRoom(context.Context, *CreateRoomRequest) (*CreateRoomResponse, error)
}

// UnimplementedRoomServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRoomServiceServer struct {
}

func (*UnimplementedRoomServiceServer) CreateRoom(ctx context.Context, req *CreateRoomRequest) (*CreateRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRoom not implemented")
}

func RegisterRoomServiceServer(s *grpc.Server, srv RoomServiceServer) {
	s.RegisterService(&_RoomService_serviceDesc, srv)
}

func _RoomService_CreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).CreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RoomService/CreateRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).CreateRoom(ctx, req.(*CreateRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RoomService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "RoomService",
	HandlerType: (*RoomServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRoom",
			Handler:    _RoomService_CreateRoom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "room.proto",
}
