name: golangci-lint

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  golangci:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: v1.53.3
