name: golangci-lint

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  golangci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: v1.53.3
